### ISSUE TITLE
业务代码正常写，数据库采用表分区能实现吗

### ISSUE THREAD

**Issue by chaoyifei** [iTraceur/django_table_sharding_example#1]
业务代码正常写，数据库采用表分区能实现吗，表中带有外键，不知道这种方法是否能正常迁移和查询

**Comment by iTraceur** [comment]
有数据库表分区的话就不需要这种方法了，但本案例方法与数据库表分区不冲突，表分区是物理上的实现，本案例是逻辑上的实现，两者互不影响，理论上是可以结合使用的，一般不建议这么做。通常情况业务上都会采用对代码零侵入性的数据库表分区方案，本案例只是另外一种设计思路，如数据库那边不支持表分区可以权衡使用这种方案。

**Comment by chaoyifei** [comment]
我有两张表需要分表，A、B， 其中B表中有个字段外键是A的id，用现有的这个demo能实现吗

**Comment by iTraceur** [comment]
@chaoyifei 不能，外键关系是需要明确表名的，这个方案表名是动态且不确定的，因此，表之间的数据关系需要在业务代码逻辑中实现。
